
#if !defined(__URLAPI)
#  define __URLAPI(...)
#endif

__URLAPI(akey2,         "^/akey/([0-9]+)$",                                "/key/<numeric>",                "\t\t\t",   "Send absolute Android key")
__URLAPI(key1,          "^/key/([a-z0-9(\\)[\\]!@#$%^&*-+=_,.;:'\"\\/])$", "/key/<numeric>/<key type>",     "\t",       "Send key by type, Android, Javascript, WINAPI, SDL2")
__URLAPI(key2,          "^/key/([0-9]+)/([0-9]+)$",                        "/key/<numeric>/<key type>",     "\t",       "Send key by type, Android, Javascript, WINAPI, SDL2")
__URLAPI(atap2,         "^/atap/([0-9]+)/([0-9]+)$",                       "/atap/<numeric X>/<numeric Y>", "\t",       "Send absolute Android tap position")
__URLAPI(tap4,          "^/tap/([0-9]+)/([0-9]+)/([0-9]+)/([0-9]+)$",      "/tap/<numeric X>/<numeric Y>/<numeric ROTATE>/<numeric RATIO>","\t","Send tap position")
__URLAPI(text,          "^/text$",                                         "/text",                         "\t\t\t\t", "Post ASCII text")
__URLAPI(stream_live,   "^/stream/live.mjpg$",                             "/stream/live.mjpg",             "\t\t",     "Get MJEPEG stream")
__URLAPI(stream_player, "^/stream/player$",                                "/stream/player",                "\t\t\t",   "Go to Web MJEPEG online player")
__URLAPI(stream_splash, "^/stream/splash.jpg$",                            "/stream/splash.jpg",            "\t\t",     "MJEPEG online player poster")
__URLAPI(capture,       "^/capture/([a-z]+)$",                             "/capture/<image ID>",           "\t\t",     "Capture screen, output ID: bmp, bmz, sdl, png, jpg")
__URLAPI(input_xml,     "^/input/info/xml$",                               "/input/info/xml",               "\t\t\t",   "Get input device information, XML format")
__URLAPI(display_xml,   "^/display/info/xml$",                             "/display/info/xml",             "\t\t",     "Get display information, XML format")
__URLAPI(client_xml,    "^/client/xml$",                                   "/client/xml",                   "\t\t\t",   "Get client information, XML format")
__URLAPI(macro_play_post,"^/macro/play$",                                  "/macro/play",                   "\t\t\t",   "Play macro posted text")
__URLAPI(macro_play_act,"^/macro/play/active$",                            "/macro/play/active",            "\t",       "Play current active macro")
__URLAPI(macro_play_id, "^/macro/play/([0-9]+)$",                          "/macro/play/<numeric ID>",      "\t",       "Play macro by ID")
__URLAPI(macro_record,  "^/macro/record$",                                 "/macro/record",                 "\t\t\t",   "Macro start record")
__URLAPI(macro_record_tm,"^/macro/record/([0-9]+)$",                       "/macro/record/<numeric>",       "\t",       "Macro start record, POST description, timeout define")
__URLAPI(macro_stop,    "^/macro/stop$",                                   "/macro/stop",                   "\t\t\t",   "Macro stop record")
__URLAPI(macro_save,    "^/macro/save$",                                   "/macro/save",                   "\t\t\t",   "Save current macro to file")
__URLAPI(macro_get,     "^/macro/get$",                                    "/macro/get",                    "\t\t\t",   "Get recorded macro")
__URLAPI(macro_get_id,  "^/macro/get/([0-9]+)$",                           "/macro/get/<numeric ID>",       "\t",       "Get recorded macro by ID")
__URLAPI(macro_list,    "^/macro/list$",                                   "/macro/list",                   "\t\t\t",   "Get saved macro list")
__URLAPI(rexit,         "^/exit$",                                         "/exit",                         "\t\t\t\t", "Stop and exit daemon immediately")
__URLAPI(lua_script,    "^/lua/script$",                                   "/lua/script",                   "\t\t\t",   "Post Lua script and run")
__URLAPI(lua_load,      "^/lua/load/(.*)$",                                "/lua/load",                     "\t\t\t",   "Load and run Lua script")
__URLAPI(lua_stop,      "^/lua/sop$",                                      "/lua/stop",                     "\t\t\t",   "Stop playing Lua script")

#undef __URLAPI
