
__KEYID(0, AKEYCODE_UNKNOWN, "Unknown key code.")
__KEYID(1, AKEYCODE_SOFT_LEFT, "Soft Left key.")
__KEYID(2, AKEYCODE_SOFT_RIGHT, "Soft Right key.")
__KEYID(3, AKEYCODE_HOM, "Home key.")
__KEYID(4, AKEYCODE_BAC, "Back key.")
__KEYID(5, AKEYCODE_CAL, "Call key.")
__KEYID(6, AKEYCODE_ENDCALL, "End Call key.")
__KEYID(7, AKEYCODE_0, "'0' key.")
__KEYID(8, AKEYCODE_1, "'1' key.")
__KEYID(9, AKEYCODE_2, "'2' key.")
__KEYID(10, AKEYCODE_3, "'3' key.")
__KEYID(11, AKEYCODE_4, "'4' key.")
__KEYID(12, AKEYCODE_5, "'5' key.")
__KEYID(13, AKEYCODE_6, "'6' key.")
__KEYID(14, AKEYCODE_7, "'7' key.")
__KEYID(15, AKEYCODE_8, "'8' key.")
__KEYID(16, AKEYCODE_9, "'9' key.")
__KEYID(17, AKEYCODE_STA, "'*' key.")
__KEYID(18, AKEYCODE_POUND, "'#' key.")
__KEYID(19, AKEYCODE_DPAD_UP, "Directional Pad Up key.")
__KEYID(20, AKEYCODE_DPAD_DOWN, "Directional Pad Down key.")
__KEYID(21, AKEYCODE_DPAD_LEFT, "Directional Pad Left key.")
__KEYID(22, AKEYCODE_DPAD_RIGHT, "Directional Pad Right key.")
__KEYID(23, AKEYCODE_DPAD_CENTER, "Directional Pad Center key.")
__KEYID(24, AKEYCODE_VOLUME_UP, "Volume Up key.")
__KEYID(25, AKEYCODE_VOLUME_DOWN, "Volume Down key.")
__KEYID(26, AKEYCODE_POWER, "Power key.")
__KEYID(27, AKEYCODE_CAMERA, "Camera key.")
__KEYID(28, AKEYCODE_CLEAR, "Clear key.")
__KEYID(29, AKEYCODE_A, "'A' key.")
__KEYID(30, AKEYCODE_B, "'B' key.")
__KEYID(31, AKEYCODE_C, "'C' key.")
__KEYID(32, AKEYCODE_D, "'D' key.")
__KEYID(33, AKEYCODE_E, "'E' key.")
__KEYID(34, AKEYCODE_F, "'F' key.")
__KEYID(35, AKEYCODE_G, "'G' key.")
__KEYID(36, AKEYCODE_H, "'H' key.")
__KEYID(37, AKEYCODE_I, "'I' key.")
__KEYID(38, AKEYCODE_J, "'J' key.")
__KEYID(39, AKEYCODE_K, "'K' key.")
__KEYID(40, AKEYCODE_L, "'L' key.")
__KEYID(41, AKEYCODE_M, "'M' key.")
__KEYID(42, AKEYCODE_N, "'N' key.")
__KEYID(43, AKEYCODE_O, "'O' key.")
__KEYID(44, AKEYCODE_P, "'P' key.")
__KEYID(45, AKEYCODE_Q, "'Q' key.")
__KEYID(46, AKEYCODE_R, "'R' key.")
__KEYID(47, AKEYCODE_S, "'S' key.")
__KEYID(48, AKEYCODE_T, "'T' key.")
__KEYID(49, AKEYCODE_U, "'U' key.")
__KEYID(50, AKEYCODE_V, "'V' key.")
__KEYID(51, AKEYCODE_W, "'W' key.")
__KEYID(52, AKEYCODE_X, "'X' key.")
__KEYID(53, AKEYCODE_Y, "'Y' key.")
__KEYID(54, AKEYCODE_Z, "'Z' key.")
__KEYID(55, AKEYCODE_COMMA, "',' key.")
__KEYID(56, AKEYCODE_PERIOD, "'.' key.")
__KEYID(57, AKEYCODE_ALT_LEF, "Left Alt modifier key.")
__KEYID(58, AKEYCODE_ALT_RIGHT, "Right Alt modifier key.")
__KEYID(59, AKEYCODE_SHIFT_LEFT, "Left Shift modifier key.")
__KEYID(60, AKEYCODE_SHIFT_RIGHT, "Right Shift modifier key.")
__KEYID(61, AKEYCODE_TAB, "Tab key.")
__KEYID(62, AKEYCODE_SPACE, "Space key.")
__KEYID(63, AKEYCODE_SYM, "Symbol modifier key.")
__KEYID(64, AKEYCODE_EXPLORE, "Explorer special function key.")
__KEYID(65, AKEYCODE_ENVELOP, "Envelope special function key.")
__KEYID(66, AKEYCODE_ENTER, "Enter key.")
__KEYID(67, AKEYCODE_DEL, "Backspace key.")
__KEYID(68, AKEYCODE_GRAVE, "'`' (backtick) key.")
__KEYID(69, AKEYCODE_MINUS, "'-'.")
__KEYID(70, AKEYCODE_EQUALS, "'=' key.")
__KEYID(71, AKEYCODE_LEFT_BRACKE, "'[' key.")
__KEYID(72, AKEYCODE_RIGHT_BRACKET, "']' key.")
__KEYID(73, AKEYCODE_BACKSLASH, "'\' key.")
__KEYID(74, AKEYCODE_SEMICOLON, "';' key.")
__KEYID(75, AKEYCODE_APOSTROPHE, "''' (apostrophe) key.")
__KEYID(76, AKEYCODE_SLASH, "'/' key.")
__KEYID(77, AKEYCODE_AT, "'@' key.")
__KEYID(78, AKEYCODE_NUM, "Number modifier key.")
__KEYID(79, AKEYCODE_HEADSETHOOK, "Headset Hook key.")
__KEYID(80, AKEYCODE_FOCUS, "Camera Focus key.")
__KEYID(81, AKEYCODE_PLU, "'+' key.")
__KEYID(82, AKEYCODE_MEN, "Menu key.")
__KEYID(83, AKEYCODE_NOTIFICATIO, "Notification key.")
__KEYID(84, AKEYCODE_SEARCH, "Search key.")
__KEYID(85, AKEYCODE_MEDIA_PLAY_PAUS, "Play/Pause media key.")
__KEYID(86, AKEYCODE_MEDIA_STOP, "Stop media key.")
__KEYID(87, AKEYCODE_MEDIA_NEXT, "Play Next media key.")
__KEYID(88, AKEYCODE_MEDIA_PREVIOUS, "Play Previous media key.")
__KEYID(89, AKEYCODE_MEDIA_REWIN, "Rewind media key.")
__KEYID(90, AKEYCODE_MEDIA_FAST_FORWARD, "Fast Forward media key.")
__KEYID(91, AKEYCODE_MUT, "Mute key.")
__KEYID(92, AKEYCODE_PAGE_UP, "Page Up key.")
__KEYID(93, AKEYCODE_PAGE_DOWN, "Page Down key.")
__KEYID(94, AKEYCODE_PICTSYMBOLS, "Picture Symbols modifier key.")
__KEYID(95, AKEYCODE_SWITCH_CHARSET, "Switch Charset modifier key.")
__KEYID(96, AKEYCODE_BUTTON_, "A Button key.")
__KEYID(97, AKEYCODE_BUTTON_, "B Button key.")
__KEYID(98, AKEYCODE_BUTTON_, "C Button key.")
__KEYID(99, AKEYCODE_BUTTON_, "X Button key.")
__KEYID(100, AKEYCODE_BUTTON_, "Y Button key.")
__KEYID(101, AKEYCODE_BUTTON_, "Z Button key.")
__KEYID(102, AKEYCODE_BUTTON_L1, "L1 Button key.")
__KEYID(103, AKEYCODE_BUTTON_R1, "R1 Button key.")
__KEYID(104, AKEYCODE_BUTTON_L2, "L2 Button key.")
__KEYID(105, AKEYCODE_BUTTON_R2, "R2 Button key.")
__KEYID(106, AKEYCODE_BUTTON_THUMBL, "Left Thumb Button key.")
__KEYID(107, AKEYCODE_BUTTON_THUMBR, "Right Thumb Button key.")
__KEYID(108, AKEYCODE_BUTTON_STAR, "Start Button key.")
__KEYID(109, AKEYCODE_BUTTON_SELECT, "Select Button key.")
__KEYID(110, AKEYCODE_BUTTON_MODE, "Mode Button key.")
__KEYID(111, AKEYCODE_ESCAPE, "Escape key.")
__KEYID(112, AKEYCODE_FORWARD_DEL, "Forward Delete key.")
__KEYID(113, AKEYCODE_CTRL_LEFT, "Left Control modifier key.")
__KEYID(114, AKEYCODE_CTRL_RIGHT, "Right Control modifier key.")
__KEYID(115, AKEYCODE_CAPS_LOCK, "Caps Lock key.")
__KEYID(116, AKEYCODE_SCROLL_LOCK, "Scroll Lock key.")
__KEYID(117, AKEYCODE_META_LEFT, "Left Meta modifier key.")
__KEYID(118, AKEYCODE_META_RIGHT, "Right Meta modifier key.")
__KEYID(119, AKEYCODE_FUNCTIO, "Function modifier key.")
__KEYID(120, AKEYCODE_SYSRQ, "System Request / Print Screen key.")
__KEYID(121, AKEYCODE_BREAK, "Break / Pause key.")
__KEYID(122, AKEYCODE_MOVE_HOME, "Home Movement key.")
__KEYID(123, AKEYCODE_MOVE_EN, "End Movement key.")
__KEYID(124, AKEYCODE_INSERT, "Insert key.")
__KEYID(125, AKEYCODE_FORWARD, "Forward key.")
__KEYID(126, AKEYCODE_MEDIA_PLAY, "Play media key.")
__KEYID(127, AKEYCODE_MEDIA_PAUSE, "Pause media key.")
__KEYID(128, AKEYCODE_MEDIA_CLOSE, "Close media key.")
__KEYID(129, AKEYCODE_MEDIA_EJECT, "Eject media key.")
__KEYID(130, AKEYCODE_MEDIA_RECOR, "Record media key.")
__KEYID(131, AKEYCODE_F1, "F1 key.")
__KEYID(132, AKEYCODE_F2, "F2 key.")
__KEYID(133, AKEYCODE_F3, "F3 key.")
__KEYID(134, AKEYCODE_F4, "F4 key.")
__KEYID(135, AKEYCODE_F5, "F5 key.")
__KEYID(136, AKEYCODE_F6, "F6 key.")
__KEYID(137, AKEYCODE_F7, "F7 key.")
__KEYID(138, AKEYCODE_F8, "F8 key.")
__KEYID(139, AKEYCODE_F9, "F9 key.")
__KEYID(140, AKEYCODE_F10, "F10 key.")
__KEYID(141, AKEYCODE_F11, "F11 key.")
__KEYID(142, AKEYCODE_F12, "F12 key.")
__KEYID(143, AKEYCODE_NUM_LOC, "Num Lock key.")
__KEYID(144, AKEYCODE_NUMPAD_0, "Numeric keypad '0' key.")
__KEYID(145, AKEYCODE_NUMPAD_1, "Numeric keypad '1' key.")
__KEYID(146, AKEYCODE_NUMPAD_2, "Numeric keypad '2' key.")
__KEYID(147, AKEYCODE_NUMPAD_3, "Numeric keypad '3' key.")
__KEYID(148, AKEYCODE_NUMPAD_4, "Numeric keypad '4' key.")
__KEYID(149, AKEYCODE_NUMPAD_5, "Numeric keypad '5' key.")
__KEYID(150, AKEYCODE_NUMPAD_6, "Numeric keypad '6' key.")
__KEYID(151, AKEYCODE_NUMPAD_7, "Numeric keypad '7' key.")
__KEYID(152, AKEYCODE_NUMPAD_8, "Numeric keypad '8' key.")
__KEYID(153, AKEYCODE_NUMPAD_9, "Numeric keypad '9' key.")
__KEYID(154, AKEYCODE_NUMPAD_DIVIDE, "Numeric keypad '/' key (for division).")
__KEYID(155, AKEYCODE_NUMPAD_MULTIPLY, "Numeric keypad '*' key (for multiplication).")
__KEYID(156, AKEYCODE_NUMPAD_SUBTRACT, "Numeric keypad '-' key (for subtraction).")
__KEYID(157, AKEYCODE_NUMPAD_ADD, "Numeric keypad '+' key (for addition).")
__KEYID(158, AKEYCODE_NUMPAD_DOT, "Numeric keypad '.' key (for decimals or digit grouping).")
__KEYID(159, AKEYCODE_NUMPAD_COMM, "Numeric keypad ',' key (for decimals or digit grouping).")
__KEYID(160, AKEYCODE_NUMPAD_ENTE, "Numeric keypad Enter key.")
__KEYID(161, AKEYCODE_NUMPAD_EQUALS, "Numeric keypad '=' key.")
__KEYID(162, AKEYCODE_NUMPAD_LEFT_PAREN, "Numeric keypad '(' key.")
__KEYID(163, AKEYCODE_NUMPAD_RIGHT_PAREN, "Numeric keypad ')' key.")
__KEYID(164, AKEYCODE_VOLUME_MUTE, "Volume Mute key.")
__KEYID(165, AKEYCODE_INF, "Info key.")
__KEYID(166, AKEYCODE_CHANNEL_UP, "Channel up key.")
__KEYID(167, AKEYCODE_CHANNEL_DOW, "Channel down key.")
__KEYID(168, AKEYCODE_ZOOM_IN, "Zoom in key.")
__KEYID(169, AKEYCODE_ZOOM_OU, "Zoom out key.")
__KEYID(170, AKEYCODE_TV, "TV key.")
__KEYID(171, AKEYCODE_WINDOW, "Window key.")
__KEYID(172, AKEYCODE_GUIDE, "Guide key.")
__KEYID(173, AKEYCODE_DVR, "DVR key.")
__KEYID(174, AKEYCODE_BOOKMAR, "Bookmark key.")
__KEYID(175, AKEYCODE_CAPTION, "Toggle captions key.")
__KEYID(176, AKEYCODE_SETTING, "Settings key.")
__KEYID(177, AKEYCODE_TV_POWE, "TV power key.")
__KEYID(178, AKEYCODE_TV_INPU, "TV input key.")
__KEYID(179, AKEYCODE_STB_POWER, "Set-top-box power key.")
__KEYID(180, AKEYCODE_STB_INPUT, "Set-top-box input key.")
__KEYID(181, AKEYCODE_AVR_POWER, "A/V Receiver power key.")
__KEYID(182, AKEYCODE_AVR_INPUT, "A/V Receiver input key.")
__KEYID(183, AKEYCODE_PROG_RE, "Red 'programmable' key.")
__KEYID(184, AKEYCODE_PROG_GREEN, "Green 'programmable' key.")
__KEYID(185, AKEYCODE_PROG_YELLOW, "Yellow 'programmable' key.")
__KEYID(186, AKEYCODE_PROG_BLUE, "Blue 'programmable' key.")
__KEYID(187, AKEYCODE_APP_SWITCH, "App switch key.")
__KEYID(188, AKEYCODE_BUTTON_, "Generic Game Pad Button #1")
__KEYID(189, AKEYCODE_BUTTON_, "Generic Game Pad Button #2")
__KEYID(190, AKEYCODE_BUTTON_, "Generic Game Pad Button #3")
__KEYID(191, AKEYCODE_BUTTON_, "Generic Game Pad Button #4")
__KEYID(192, AKEYCODE_BUTTON_, "Generic Game Pad Button #5")
__KEYID(193, AKEYCODE_BUTTON_, "Generic Game Pad Button #6")
__KEYID(194, AKEYCODE_BUTTON_, "Generic Game Pad Button #7")
__KEYID(195, AKEYCODE_BUTTON_, "Generic Game Pad Button #8")
__KEYID(196, AKEYCODE_BUTTON_, "Generic Game Pad Button #9")
__KEYID(197, AKEYCODE_BUTTON_10, "Generic Game Pad Button #10")
__KEYID(198, AKEYCODE_BUTTON_11, "Generic Game Pad Button #11")
__KEYID(199, AKEYCODE_BUTTON_12, "Generic Game Pad Button #12")
__KEYID(200, AKEYCODE_BUTTON_13, "Generic Game Pad Button #13")
__KEYID(201, AKEYCODE_BUTTON_14, "Generic Game Pad Button #14")
__KEYID(202, AKEYCODE_BUTTON_15, "Generic Game Pad Button #15")
__KEYID(203, AKEYCODE_BUTTON_16, "Generic Game Pad Button #16")
__KEYID(204, AKEYCODE_LANGUAGE_SWITCH, "Language Switch key.")
__KEYID(205, AKEYCODE_MANNER_MODE, "Manner Mode key.")
__KEYID(206, AKEYCODE_3D_MODE, "3D Mode key.")
__KEYID(207, AKEYCODE_CONTACT, "Contacts special function key.")
__KEYID(208, AKEYCODE_CALENDA, "Calendar special function key.")
__KEYID(209, AKEYCODE_MUSIC, "Music special function key.")
__KEYID(210, AKEYCODE_CALCULATOR, "Calculator special function key.")
__KEYID(211, AKEYCODE_ZENKAKU_HANKAKU, "Japanese full-width / half-width key.")
__KEYID(212, AKEYCODE_EIS, "Japanese alphanumeric key.")
__KEYID(213, AKEYCODE_MUHENKA, "Japanese non-conversion key.")
__KEYID(214, AKEYCODE_HENKAN, "Japanese conversion key.")
__KEYID(215, AKEYCODE_KATAKANA_HIRAGANA, "Japanese katakana / hiragana key.")
__KEYID(216, AKEYCODE_YEN, "Japanese Yen key.")
__KEYID(217, AKEYCODE_RO, "Japanese Ro key.")
__KEYID(218, AKEYCODE_KAN, "Japanese kana key.")
__KEYID(219, AKEYCODE_ASSIST, "Assist key.")
__KEYID(220, AKEYCODE_BRIGHTNESS_DOWN, "Brightness Down key.")
__KEYID(221, AKEYCODE_BRIGHTNESS_UP, "Brightness Up key.")
__KEYID(222, AKEYCODE_MEDIA_AUDIO_TRACK, "Audio Track key.")
__KEYID(223, AKEYCODE_SLEEP, "Sleep key.")
__KEYID(224, AKEYCODE_WAKEUP, "Wakeup key.")
__KEYID(225, AKEYCODE_PAIRING, "Pairing key.")
__KEYID(226, AKEYCODE_MEDIA_TOP_MENU, "Media Top Menu key.")
__KEYID(227, AKEYCODE_11, "'11' key.")
__KEYID(228, AKEYCODE_12, "'12' key.")
__KEYID(229, AKEYCODE_LAST_CHANNE, "Last Channel key.")
__KEYID(230, AKEYCODE_TV_DATA_SERVICE, "TV data service key.")
__KEYID(231, AKEYCODE_VOICE_ASSIS, "Voice Assist key.")
__KEYID(232, AKEYCODE_TV_RADIO_SERVICE, "Radio key.")
__KEYID(233, AKEYCODE_TV_TELETEXT, "Teletext key.")
__KEYID(234, AKEYCODE_TV_NUMBER_ENTRY, "Number entry key.")
__KEYID(235, AKEYCODE_TV_TERRESTRIAL_ANALOG, "Analog Terrestrial key.")
__KEYID(236, AKEYCODE_TV_TERRESTRIAL_DIGITAL, "Digital Terrestrial key.")
__KEYID(237, AKEYCODE_TV_SATELLIT, "Satellite key.")
__KEYID(238, AKEYCODE_TV_SATELLITE_BS, "BS key.")
__KEYID(239, AKEYCODE_TV_SATELLITE_CS, "CS key.")
__KEYID(240, AKEYCODE_TV_SATELLITE_SERVICE, "BS/CS key.")
__KEYID(241, AKEYCODE_TV_NETWORK, "Toggle Network key.")
__KEYID(242, AKEYCODE_TV_ANTENNA_CABLE, "Antenna/Cable key.")
__KEYID(243, AKEYCODE_TV_INPUT_HDMI_1, "HDMI #1 key.")
__KEYID(244, AKEYCODE_TV_INPUT_HDMI_2, "HDMI #2 key.")
__KEYID(245, AKEYCODE_TV_INPUT_HDMI_3, "HDMI #3 key.")
__KEYID(246, AKEYCODE_TV_INPUT_HDMI_4, "HDMI #4 key.")
__KEYID(247, AKEYCODE_TV_INPUT_COMPOSITE_1, "Composite #1 key.")
__KEYID(248, AKEYCODE_TV_INPUT_COMPOSITE_2, "Composite #2 key.")
__KEYID(249, AKEYCODE_TV_INPUT_COMPONENT_1, "Component #1 key.")
__KEYID(250, AKEYCODE_TV_INPUT_COMPONENT_2, "Component #2 key.")
__KEYID(251, AKEYCODE_TV_INPUT_VGA_1, "VGA #1 key.")
__KEYID(252, AKEYCODE_TV_AUDIO_DESCRIPTION, "Audio description key.")
__KEYID(253, AKEYCODE_TV_AUDIO_DESCRIPTION_MIX_UP, "Audio description mixing volume up key.")
__KEYID(254, AKEYCODE_TV_AUDIO_DESCRIPTION_MIX_DOWN, "Audio description mixing volume down key.")
__KEYID(255, AKEYCODE_TV_ZOOM_MOD, "Zoom mode key, mode (Normal, Full, Zoom, Wide-zoom..)")
__KEYID(256, AKEYCODE_TV_CONTENTS_MENU, "Contents menu key. Goes to the title list.")
__KEYID(257, AKEYCODE_TV_MEDIA_CONTEXT_MENU, "Media context menu key, menu (0x11) of CEC User Control Code.")
__KEYID(258, AKEYCODE_TV_TIMER_PROGRAMMING, "Timer programming key. Goes to the timer recording menu.")
__KEYID(259, AKEYCODE_HEL, "Help key.")
__KEYID(260, AKEYCODE_NAVIGATE_PREVIOUS, "Navigate prev.")
__KEYID(261, AKEYCODE_NAVIGATE_NEXT, "Navigate next.")
__KEYID(262, AKEYCODE_NAVIGATE_IN, "Navigate in.")
__KEYID(263, AKEYCODE_NAVIGATE_OU, "Navigate out.")
__KEYID(264, AKEYCODE_STEM_PRIMARY, "Primary stem key power/reset button on watch.")
__KEYID(265, AKEYCODE_STEM_1, "Generic stem key 1 for Wear")
__KEYID(266, AKEYCODE_STEM_2, "Generic stem key 2 for Wear")
__KEYID(267, AKEYCODE_STEM_3, "Generic stem key 3 for Wear")
__KEYID(268, AKEYCODE_DPAD_UP_LEF, "Directional Pad Up-Left")
__KEYID(269, AKEYCODE_DPAD_DOWN_LEFT, "Directional Pad Down-Left")
__KEYID(270, AKEYCODE_DPAD_UP_RIGHT, "Directional Pad Up-Right")
__KEYID(271, AKEYCODE_DPAD_DOWN_RIGHT, "Directional Pad Down-Right")
__KEYID(272, AKEYCODE_MEDIA_SKIP_FORWARD, "Skip forward media key")
__KEYID(273, AKEYCODE_MEDIA_SKIP_BACKWARD, "Skip backward media key")
__KEYID(274, AKEYCODE_MEDIA_STEP_FORWARD, "Step forward media key.")
__KEYID(275, AKEYCODE_MEDIA_STEP_BACKWARD, "Step backward media key.")
__KEYID(276, AKEYCODE_SOFT_SLEEP, "Put device to sleep unless a wakelock is held.")
__KEYID(277, AKEYCODE_CUT, "Cut key.")
__KEYID(278, AKEYCODE_COPY, "Copy key.")
__KEYID(279, AKEYCODE_PASTE, "Paste key.")
__KEYID(280, AKEYCODE_SYSTEM_NAVIGATION_UP, "fingerprint navigation key, up.")
__KEYID(281, AKEYCODE_SYSTEM_NAVIGATION_DOWN, "fingerprint navigation key, down.")
__KEYID(282, AKEYCODE_SYSTEM_NAVIGATION_LEFT, "fingerprint navigation key, left.")
__KEYID(283, AKEYCODE_SYSTEM_NAVIGATION_RIGHT, "fingerprint navigation key, right.")
__KEYID(284, AKEYCODE_ALL_APPS, "All apps")
__KEYID(285, AKEYCODE_REFRESH, "Refresh key")
__KEYID(286, AKEYCODE_THUMBS_UP, "Thumbs up key. Apps can use this to let user upvote content.")
__KEYID(287, AKEYCODE_THUMBS_DOWN, "Thumbs down key. Apps can use this to let user downvote content.")
__KEYID(288, AKEYCODE_PROFILE_SWITCH, "Used to switch current account that is consuming content. ")
__KEYID(330, AKEYCODE____NOT_DEFINED, "Unknown hardware key code.. ")

#undef __KEYID
